version: "2"
run:
  allow-parallel-runners: true
linters:
  default: all
  disable:
    - cyclop
    - depguard
    - err113
    - exhaustruct
    - funlen
    - gochecknoglobals
    - gochecknoinits
    - gocyclo
    - godox
    - mnd
    - nlreturn
    - noinlineerr
    - paralleltest
    - unparam
    - wrapcheck
    - wsl
    - wsl_v5
  settings:
    revive:
      enable-all-rules: true
      rules:
        - name: if-return
          disabled: true
        - name: cognitive-complexity
          disabled: true
        - name: function-length
          disabled: true
        - name: argument-limit
          disabled: true
        - name: cyclomatic
          disabled: true
        - name: add-constant
          disabled: true
        - name: line-length-limit
          disabled: true
        - name: max-public-structs
          disabled: true
        - name: struct-tag
          disabled: true
        - name: dot-imports
          disabled: true
        - name: confusing-results
          disabled: true
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - gosec
        path: test/e2e
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
    - gofumpt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
