run:
  concurrency: 0
  timeout: 5m
  allow-parallel-runners: true

linters-settings:
  revive:
    enable-all-rules: true
    rules:
      - name: if-return
        disabled: true
      - name: cognitive-complexity
        disabled: true
      - name: function-length
        disabled: true
      - name: argument-limit
        disabled: true
      - name: cyclomatic
        disabled: true
      - name: add-constant
        disabled: true
      - name: line-length-limit
        disabled: true
      - name: max-public-structs
        disabled: true
      - name: struct-tag
        disabled: true
      - name: dot-imports
        disabled: true

linters:
  enable-all: true
  disable:
    - gocyclo
    - unparam
    - nlreturn
    - godox
    - wrapcheck
    - paralleltest
    - mnd
    - gochecknoglobals
    - err113
    - cyclop
    - gochecknoinits
    - wsl
    - exhaustruct
    - gci
    - funlen
    - depguard
    - exportloopref # deprecated

issues:
  exclude-rules:
    - path: test/e2e
      linters:
        - gosec
