// Code generated by "stringer -type=deployStatusType"; DO NOT EDIT.

package controller

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[deployStatusUnknown-8]
	_ = x[deployStatusNotFound-9]
	_ = x[deployStatusReady-10]
	_ = x[deployStatusNotReady-11]
}

const _deployStatusType_name = "deployStatusUnknowndeployStatusNotFounddeployStatusReadydeployStatusNotReady"

var _deployStatusType_index = [...]uint8{0, 19, 39, 56, 76}

func (i deployStatusType) String() string {
	i -= 8
	if i < 0 || i >= deployStatusType(len(_deployStatusType_index)-1) {
		return "deployStatusType(" + strconv.FormatInt(int64(i+8), 10) + ")"
	}
	return _deployStatusType_name[_deployStatusType_index[i]:_deployStatusType_index[i+1]]
}
