// Code generated by "stringer -type=deployStatusType"; DO NOT EDIT.

package controller

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[deployStatusUnknown-0]
	_ = x[deployStatusNotFound-1]
	_ = x[deployStatusReady-2]
	_ = x[deployStatusNotReady-3]
}

const _deployStatusType_name = "deployStatusUnknowndeployStatusNotFounddeployStatusReadydeployStatusNotReady"

var _deployStatusType_index = [...]uint8{0, 19, 39, 56, 76}

func (i deployStatusType) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_deployStatusType_index)-1 {
		return "deployStatusType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _deployStatusType_name[_deployStatusType_index[idx]:_deployStatusType_index[idx+1]]
}
