// Code generated by "stringer -type=whatToDoType"; DO NOT EDIT.

package controller

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[shouldCreatePreMigrationJob-9]
	_ = x[shouldCreatePostMigrationJob-10]
	_ = x[shouldSetMigratingStatus-11]
	_ = x[shouldUnsetMigratingStatus-12]
	_ = x[shouldCreateOrUpdateDeploysWithSpec-13]
	_ = x[shouldCreateOrUpdateDeploysWithMigratingImages-14]
	_ = x[shouldDeletePostMigrationJob-15]
	_ = x[shouldDeletePreMigrationJob-16]
	_ = x[shouldDoNothing-17]
}

const _whatToDoType_name = "shouldCreatePreMigrationJobshouldCreatePostMigrationJobshouldSetMigratingStatusshouldUnsetMigratingStatusshouldCreateOrUpdateDeploysWithSpecshouldCreateOrUpdateDeploysWithMigratingImagesshouldDeletePostMigrationJobshouldDeletePreMigrationJobshouldDoNothing"

var _whatToDoType_index = [...]uint16{0, 27, 55, 79, 105, 140, 186, 214, 241, 256}

func (i whatToDoType) String() string {
	idx := int(i) - 9
	if i < 9 || idx >= len(_whatToDoType_index)-1 {
		return "whatToDoType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _whatToDoType_name[_whatToDoType_index[idx]:_whatToDoType_index[idx+1]]
}
