apiVersion: v1
kind: Service
metadata:
  name: {{ include "magout.fullname" . }}-web
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  ports:
    - port: 3000
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: puma
    app.kubernetes.io/component: web
    app.kubernetes.io/part-of: mastodon
    magout.anqou.net/mastodon-server: {{ include "magout.fullname" . }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "magout.fullname" . }}-streaming
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  ports:
    - port: 4000
      targetPort: streaming
      protocol: TCP
      name: streaming
  selector:
    app.kubernetes.io/name: node
    app.kubernetes.io/component: streaming
    app.kubernetes.io/part-of: mastodon
    magout.anqou.net/mastodon-server: {{ include "magout.fullname" . }}
